### ISSUE TITLE
Various dump calls crash

### ISSUE THREAD

**Issue by chrisvam** [slaclab/cameralink-gateway#23]
Hi Larry,

We're upgrading to your latest releases and I believe the lines after this one are making us crash because we don't run from the same directory as you do, so the "dump/" directory doesn't exist:

https://github.com/slaclab/cameralink-gateway/blob/2f0d7a207606f3f86b052e5d0c12d801f459ad72/firmware/python/cameralink_gateway/_ClinkDevRoot.py#L230

There's a similar set of lines later on as well:

https://github.com/slaclab/cameralink-gateway/blob/2f0d7a207606f3f86b052e5d0c12d801f459ad72/firmware/python/cameralink_gateway/_ClinkDevRoot.py#L329

Not sure how you want to address this, hence the "issue" vs. a PR.  Thanks...

chris

**Comment by ruck314** [comment]
We issue track on JIRA. 
https://jira.slac.stanford.edu/browse/ESCLINK-33
